# don't forget to update config.model
environment: sit

app:
  name: champ-user-producer

server:
  port: 8080
  writetimeout: 15
  readtimeout: 15
  idletimeout: 60
  ctx-timeout: 10
  force-retry: true

log:
  environment: production
  level: info
  format: json

postgres:
  db-name: champ-db
  host: 172.28.240.42
  port: 5432
  pool-size: 30

kafka:
  address: 
    - kafka.poc.internal:9092
  topic: 
    - CreateUserEventCHAMP

redis:
  address: 172.28.241.3:6379
  database: 1

user-list-key: USER_LIST_CHAMP





